### PR TITLE
Update suggested changes for hammerhead

### PR DESCRIPTION
**Pull request by axet**
Update all binary files with source information. Based on #1 analysis

### CODE REVIEW

**Comment by z3DD3r** [comment]
I guess you get something wrong. We don’t need to update anything. Also some blobs were patched (changed some paths for example) and it will be hard to find original blobs. And what for? Why are you trying to find the original blobs? They most likely will not work correctly without patches. Moreover, why you wanna use libqti-perfd-client.so from OnePlus 3T and mpdecision from Bacon? These two blobs were taken from samsung klte and they are works without any issues….

**Comment by axet** [comment]
I'm only suggest to update some of your blobs which sources are unknown. They are very suspicious and replace it by blobs from other LineageOS 18.1 official builds.

For example nexus 5 apks does not comes from hammerhead-m4b30x, which is stated by commit. So it comes from unknown source, may be malicious. I update it from hammerhead-m4b30x as commit says.

Also,libqti-perfd-client.so updated from unknown source, I revert it from official lineageos-18.1 d802 device. It already have been in the repo and changed by someone here eafcb8de.

And so on...

**Comment by z3DD3r** [comment]
It they are suspicious for you then you can use another roms. libqti-perd-client.so used from here: https://github.com/TheMuppets/proprietary_vendor_samsung/commit/ba4391bb9c90f07846fe325b61297b9331210b51. But even such blobs maybe patched to work properly on hammerhead. Anyway i will not approve any pull requests with blobs changes without proper testing. And because i don’t have this device anymore i will never approve such pull requests….

**Comment by z3DD3r** [comment]
Here are some notes about files you changed. 

hammerhead/proprietary/vendor/app/UpdateSetting/UpdateSetting.apk
hammerhead/proprietary/vendor/app/qcrilmsgtunnel/qcrilmsgtunnel.apk
hammerhead/proprietary/vendor/app/shutdownlistener/shutdownlistener.apk
These apps was changed here (I think these apps were also deodexed by razorloves): https://github.com/z3DD3r/android_vendor_lge/commit/a0bd37c8287b3ddf7efd140b22227c6a9d75030b


hammerhead/proprietary/vendor/bin/mpdecision
hammerhead/proprietary/vendor/bin/libqti-perfd-client.so 
These are taken from samsung klte: https://github.com/TheMuppets/proprietary_vendor_samsung/commit/ba4391bb9c90f07846fe325b61297b9331210b51


hammerhead/proprietary/vendor/bin/sensors.qcom
This was changed here: https://github.com/z3DD3r/android_vendor_lge/commit/e1c6d9703c684c7f7f8b4cea59935b8a6e6854f1


hammerhead/proprietary/vendor/framework/qcrilhook.jar
This was changed here (I think it also was deoxed by razorloves): https://github.com/z3DD3r/android_vendor_lge/commit/a0bd37c8287b3ddf7efd140b22227c6a9d75030b


hammerhead/proprietary/vendor/lib/libdrmdiag.so
This was changed here (and as far as i know it is unused because we use different DRM blobs which doesn't require libdrmdiag.so): https://github.com/z3DD3r/android_vendor_lge/commit/27281f779760d45cb9e4e0126b8efb477783911a


hammerhead/proprietary/vendor/lib/libloc_ds_api.so
This was changed here: https://github.com/z3DD3r/android_vendor_lge/commit/cddf7d2f39b33965806b02653aac8971d0b66a46


hammerhead/proprietary/vendor/lib/soundfx/libqcbassboost.so
hammerhead/proprietary/vendor/lib/soundfx/libqcreverb.so
hammerhead/proprietary/vendor/lib/soundfx/libqcvirt.so
These was added here: https://github.com/z3DD3r/android_vendor_lge/commit/932f1febde2ff0a122d36ecbf04b9a523e505e37


Blobs from Bacon and G2 are not always a good choice for hammerhead. For example mpdecision and libqti-perfd-client.so  from samsung klte works better and doesn't require additional shims for newer versions of android. I suggest you to get more details about what and why was changed before making changes to the proprietary blobs...

**Comment by axet** [comment]
Much better. Almost all binaries are covered. You were right, files from Bacon does not work well on hammerhead, I was too hurry to upload and pull request it.  I should test it out first more carefully. But after an update my hammerhead finally start to see all satellites 8/24, before the update it only showing 1/1 or 0/1 of satellites.

I'm adding lineage-18.1-20220821-nightly-klte-signed to the firmware list. It is indeed covering for:

* mpdecision
* eglsubAndroid.so
* libEGL_adreno.so
* libGLESv2_adreno.so 
* flp.default.so
* libwvdrmengine.so
* libC2D2.so
* libCB.so
* libOpenCL.so
* libadreno_utils.so
* libc2d30-a3xx.so
* libflp.so
* libgeofence.so
* libgsl.so
* libizat_core.so
* liblbs_core.so
* libllvm-qcom.so
* libloc_api_v02.so
* libprotobuf-cpp-lite-v29.so
* libsc-a3xx.so
* libscale.so
* libloc_ds_api.so
* libqti-perfd-client.so

Following did come from Nexus 5 MRA58K:

* libdrmdiag.so

seonsors comes from hammerhead-m4b30x

* sensors.qcom

But still I have few firmware blogs missing:

The following files comes from 932f1feb, but no original source as well:

* soundfx/libqcbassboost.so
* soundfx/libqcreverb.so
* soundfx/libqcvirt.so


The following, comes from a0bd37c8, but what the firmware file? If it is deodexed, I have no idea how can I confirm it. Maybe better to replace it with original files? At least, separate commits with original files + deodexing.

* UpdateSetting.apk 
* qcrilmsgtunnel.apk
* shutdownlistener.apk
* qcrilhook.jar

That is it. Only those files are left to find out. Thank you for helping it out!

**Comment by z3DD3r** [comment]
libloc_ds_api.so:

- This file is actually taken from bacon. Some details here: https://github.com/z3DD3r/android_device_lge_hammerhead/commit/9b8bf8a3491e09a4c9c1a5f3c0e4d53697703ce7
- Nobody reported any problems with GPS so i can't be sure that is a good idea to update this blob. It maybe your specific issue.

libqcbassboost.so, libqcreverb.so, libqcvirt.so:

- Can't say where these files from.
- Anyway i didn't see any reason to not trust LineageOS developers especially myfluxi and razorloves

UpdateSetting.apk, qcrilmsgtunnel.apk, shutdownlistener.apk, qcrilhook.jar

- About deodexing https://forum.xda-developers.com/t/complete-guide-what-is-odex-and-deodex-rom.2200349
- I guess that the only way to check these files is to get them from M4B30X factory image and compare classes between original apk/jar and deodexed
- If i remember correctly these files were also patched in https://github.com/z3DD3r/android_vendor_lge/commit/e1c6d9703c684c7f7f8b4cea59935b8a6e6854f1 to support new paths in /vendor/
- And as i told earlier, i didn't see any reason to not trust LineageOS developers especially myfluxi and razorloves. Moreover razorloves was the official maintainer of hammerhead from LineageOS team

**Comment by axet** [comment]
Confirming: a0bd37c8 hammerhead-m4b30x are deodexed, you can check it by unpacking classes.dex into *.smali:

* ./proprietary/vendor/app/UpdateSetting/UpdateSetting.apk
* ./proprietary/vendor/app/qcrilmsgtunnel/qcrilmsgtunnel.apk
* ./proprietary/vendor/app/shutdownlistener/shutdownlistener.apk
* ./proprietary/vendor/framework/qcrilhook.jar

**Comment by z3DD3r** [comment]
@axet,
Nice! So the only question is about soundfx libs. But unfortunately i can't help you here. These libs maybe from any device and any Android version. Most likely these blobs are from some Android L rom because https://github.com/z3DD3r/android_vendor_lge/commit/932f1febde2ff0a122d36ecbf04b9a523e505e37 commit was made before Android M release. Also it is not a good idea to update them from latest build for Bacon. Bacon uses CAF versions of kernel and qcom audio stack. These libs may not work for hammerhead because we use AOSP based kernel and QCOM audio stack...

**Pull request closed without merging**
